dependencies:
  - name: acme-middleware
    version: 3.0.0
    repository: https://artifactory-tools.cp4appl-demo-cluster-atci-83bcef15400c39e8de4fdef573e95a5c-0000.us-south.containers.appdomain.cloud/artifactory/generic-local/airbgspain
