apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: deploy-using-acm-run-1
  namespace: acme-cicd
  labels:
    tekton.dev/pipeline: deploy-using-acm
spec:
  params:
    - name: deployment-name
      value: acme-1
    - name: git-url
      value: 'https://apikey:ipm9RgA5NSPp-yLJu2dz@eu-de.git.cloud.ibm.com/airbg-spain/internal-demos/cloud-paks-demos/gitops-acme.git'
    - name: git-revision
      value: master
  pipelineRef:
    name: deploy-using-acm
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: source-pvc