---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: acme-acm-placement-ui
  namespace: acme-acm
  labels:
    app: acme-insurances
spec:
  clusterSelector:
    matchLabels:
      env: lab
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: acme-acm-placement-dev
  namespace: acme-acm
  labels:
    app: acme-insurances
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterReplicas: 2
  clusterSelector:
    matchExpressions:
      - key: env
        operator: In
        values:
          - dev
          - local
      - key: cloud
        operator: NotIn
        values:
          - Google
