---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: acme-acm-subscription-ui
  namespace: acme-acm
  annotations: {}
  labels:
    app: acme-insurances
spec:
  name: acme-ui
  channel: acme-acm/acme-channel-dockerhub
  packageOverrides:
    - packageAlias: acme-ui
      packageName: acme-ui
  placement:
    placementRef:
      name: acme-acm-placement-ui
      kind: PlacementRule
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: acme-acm-subscription-middleware
  namespace: acme-acm
  annotations: {}
  labels:
    app: acme-insurances
spec:
  name: acme-middleware
  channel: acme-acm/acme-channel-dockerhub
  packageOverrides:
    - packageAlias: acme-middleware
      packageName: acme-middleware
  placement:
    placementRef:
      name: acme-acm-placement-dev
      kind: PlacementRule
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: acm-acm-subscription-database-connector
  namespace: acme-acm
  annotations: {}
  labels:
    app: acme-insurances
spec:
  name: acme-database-connector
  channel: acme-acm/acme-channel-dockerhub
  packageOverrides:
    - packageAlias: acme-database-connector
      packageName: acme-database-connector
  placement:
    placementRef:
      name: acme-acm-placement-dev
      kind: PlacementRule