apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: acme-cicd-acm-trigger-binding
  generation: 1
  namespace: acme-cicd
  labels:
    app: acme-cicd-acm
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.url)
