apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: acme-cicd-acm
  namespace: acme-cicd
  labels:
    app: acme-cicd-acm
spec:
  params:
    - description: Deployment name
      name: deploymentname
    - description: The git revision
      name: gitrevision
    - description: The git repository url
      name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: deploy-using-acm-
      spec:
        params:
          - name: deployment-name
            value: $(params.deploymentname)
          - name: git-url
            value: $(params.gitrepositoryurl)
          - name: git-revision
            value: $(params.gitrevision)
        pipelineRef:
          name: deploy-using-acm
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
          - name: shared-workspace
            persistentvolumeclaim:
              claimName: source-pvc
